### ISSUE TITLE
bug: Failed to run app.py on start

### ISSUE THREAD

**Issue by withsmilo** [line/jnotebook_reader#17]
Hi, long time no see. :)
I'm trying to use the jnotebook_reader for internal jupyter notebook users, but I've met an error on starting app.py. I will create a pull request soon to fix this.

```
% python app.py
Traceback (most recent call last):
  File "app.py", line 16, in <module>
    from flask import Flask
  File "/opt/anaconda3/envs/jnotebook_reader_py38_2/lib/python3.8/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/opt/anaconda3/envs/jnotebook_reader_py38_2/lib/python3.8/site-packages/jinja2/__init__.py)
```

**Comment by mars-martin-line** [comment]
LGTM
